import './globals.css';

import { Inter } from 'next/font/google';
import Navigation from './components/layout/navigation'
import AuthContext from './context/auth-context';
const inter = Inter({ subsets: ['latin']});


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
        <>
        <Navigation /> 
        </>
        {children}
        </AuthContext>
        </body>
    </html>
  )
}
